---
apiVersion: lmtd.lifememory.team/v1beta1
kind: Challenge
labels:
  # [この設定固有の識別子の設定]
  importer.lmtd.lifememory.team/unique-key: challenge-whisky
spec:
  # [問題名の設定]
  name: whisky

  # タグ
  tag:
    - author:ptr-yudai

  # [表示順の設定]
  # ※ この値については何もしなくて大丈夫です
  order: 3

  # [公開設定]
  # ※ この値については何もしなくて大丈夫です
  isPublic: true

  # [ジャンルの設定]
  ownerCategoryUniqueKey: category-reversing

  # [配布ファイルの設定]
  dists:
  - name: "backdoor_plugin.so"
    uploadType: raw
    replaceKey: "<DISTFILE>"

  # [問題文の設定]
  description: |
    Do you like [whisky](http://{HOST}:8080/)?<br>
    Read <code>/flag.txt</code> to get the flag!

    <DISTFILE>

  server:
    ports:
      - 8080
    protocol: tcp
    docker: true
    plan: small
    tags: ["filter:outbound_block", "filter:inbound_block"]
