---
apiVersion: lmtd.lifememory.team/v1beta1
kind: Flag
labels:
  # [この設定固有の識別子の設定]
  importer.lmtd.lifememory.team/unique-key: flag-abyss
spec:
  # [設定対象の設定]
  ownerChallengeUniqueKey: challenge-abyss

  # [フラグの設定]
  content: SECCON{SeaBIOS_SMI_pr0gr4m_1s_4ctu4lly_n0t_pr0t3ct3d}

  # [初期得点の設定]
  # 変更しないでください。
  point: 300
